substitutions:
  # For available substitutions check out
  #  https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
  _MVN_DOTNET_VERSION: 2.2.301-3-jdk-12-slim

steps:
    # clone repo
  - id: 'git-clone'
    waitFor: ['-']
    name: 'gcr.io/cloud-builders/git'
    dir: /builder/home/
    args: ['clone', 'https://github.com/tapwater/cloud-build-test.git']
  - id: 'git'
    waitFor: ['-']
    name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/sh'
    args:
      - -c
      - |
        (
          ls -al . && \
          ls -al ../ 
        ) || echo 'Error'



